name: Add podcast
on:
  issues:
    types:
      - labeled
permissions:
  contents: write
  issues: write
concurrency: 'main'
jobs:
  add_podcast:
    if: github.event.label.name == 'podcast-approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-podcast.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > add-podcast.json

      - run: cat add-podcast.json

      - run: node ./scripts/add-podcast.js

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git add angular-hub/src/public/assets/data/podcast.json && \
          git commit -m 'Add podcast' && \
          git push

      - uses: peter-evans/close-issue@v1
        with:
          comment: 'Podcast added: thanks for your contribution!'
